import Head from 'next/head';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Website</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading='Vik"s Photography'
        message="I capture moments in nature and keep them alive."
      />
      <Navbar />
    </div>
  );
}
